const D=window.GAME_DATA;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const EMOJIS=['🦆','🐸','🦝','🦊','🐙','🦈','🐔','🦖','🦄','🐗','🐧','🦀','🐌','🦇','🐝','🦞','🦧','🐊','🦦','🐏','🦜','🐡','🦩','🦥','🐈','🐕','🦔','🐢','🐐','🦬','🦭','🦚','🐍','🦎','🐀','🐓','🦃','🦨','🦡','🐒'];
let mode='host', avatar=pick(EMOJIS), peer=null, hostConn=null, conns=new Map(), room='', me=null;
let state={players:[],phase:'lobby',round:0,totalRounds:5,writeTime:60,prompt:'',answers:[],votes:{},scores:{},usedPrompts:[]};
let timerHandle=null, localSubmitted=false, localVoted=false;
function pick(a){return a[Math.floor(Math.random()*a.length)]}
function id(){return Math.random().toString(36).slice(2,10)}
function screen(name){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+name).classList.add('active')}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800)}
function setBadge(t){$('#connectionBadge').textContent=t}
function updateAvatar(){ $('#avatarPreview').textContent=avatar }
updateAvatar();
$('#rerollAvatar').onclick=()=>{let n=avatar;while(n===avatar)n=pick(EMOJIS);avatar=n;updateAvatar()}
$('#hostBtn').onclick=()=>{mode='host';$('#joinFields').classList.add('hidden');screen('profile')}
$('#joinOpenBtn').onclick=()=>{mode='guest';$('#joinFields').classList.remove('hidden');screen('profile')}
$$('.back').forEach(b=>b.onclick=()=>screen('home'));
$('#profileContinue').onclick=()=>{const nick=$('#nickname').value.trim();if(!nick)return toast('Choisis un pseudo.');me={id:id(),nick,avatar}; mode==='host'?createRoom():joinRoom($('#roomCode').value.trim().toUpperCase())}
function roomId(code){return 'suite-ou-crash-'+code.toLowerCase()}
function makeCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return Array.from({length:6},()=>pick(chars)).join('')}
function createRoom(){room=makeCode(); peer=new Peer(roomId(room)); peer.on('open',()=>{state.players=[me];state.scores[me.id]=0;enterLobby();setBadge('Hôte · '+room)});peer.on('connection',c=>{c.on('open',()=>{});c.on('data',m=>hostReceive(c,m));c.on('close',()=>removeConn(c.peer))});peer.on('error',e=>toast('Connexion : '+e.type))}
function joinRoom(code){if(!code)return toast('Entre le code de partie.');room=code;peer=new Peer();peer.on('open',()=>{hostConn=peer.connect(roomId(room),{reliable:true});hostConn.on('open',()=>{hostConn.send({type:'join',player:me});setBadge('Connecté · '+room)});hostConn.on('data',guestReceive);hostConn.on('close',()=>{setBadge('Hôte déconnecté');toast("L'hôte a quitté la partie.")});hostConn.on('error',()=>toast('Connexion impossible.'))});peer.on('error',e=>toast('Connexion : '+e.type))}
function hostReceive(c,m){if(m.type==='join'){if(state.phase!=='lobby')return c.send({type:'error',text:'Partie déjà lancée.'});if(state.players.some(p=>p.nick.toLowerCase()===m.player.nick.toLowerCase()))m.player.nick+='²';conns.set(m.player.id,c);state.players.push(m.player);state.scores[m.player.id]=0;broadcast();renderLobby();return}if(m.type==='answer'&&state.phase==='write'){if(!state.answers.some(a=>a.playerId===m.playerId)){state.answers.push({id:id(),playerId:m.playerId,text:m.text});broadcast();renderWriteProgress();if(state.answers.length===state.players.length)beginVote()}}if(m.type==='vote'&&state.phase==='vote'){state.votes[m.playerId]=m.answerId;broadcast();if(Object.keys(state.votes).length===state.players.length)finishVote()}}
function guestReceive(m){if(m.type==='state'){state=m.state;routeState()}else if(m.type==='error')toast(m.text)}
function removeConn(peerId){for(const [pid,c] of conns)if(c.peer===peerId){conns.delete(pid);state.players=state.players.filter(p=>p.id!==pid);broadcast();routeState();break}}
function broadcast(){const msg={type:'state',state};for(const c of conns.values())if(c.open)c.send(msg)}
function enterLobby(){screen('lobby');$('#roomLabel').textContent=room;$('#hostControls').classList.toggle('hidden',mode!=='host');$('#guestWaiting').classList.toggle('hidden',mode==='host');renderLobby()}
function renderLobby(){if($('#lobby').classList.contains('active')){$('#roomLabel').textContent=room;$('#players').innerHTML=state.players.map(p=>`<div class="player"><div class="avatar">${p.avatar}</div><div><b>${esc(p.nick)}</b>${p.id===state.players[0]?.id?'<div class="muted">Hôte</div>':''}</div></div>`).join('')}}
$('#copyCode').onclick=async()=>{await navigator.clipboard.writeText(room);toast('Code copié : '+room)}
$('#startBtn').onclick=()=>{if(state.players.length<2)return toast('Il faut au moins 2 joueurs.');state.totalRounds=+$('#roundCount').value;state.writeTime=+$('#writeTime').value;state.round=0;startRound()}
function newPrompt(){let choices=D.prompts.filter((_,i)=>!state.usedPrompts.includes(i));if(!choices.length){state.usedPrompts=[];choices=D.prompts}let text=pick(choices);let idx=D.prompts.indexOf(text);state.usedPrompts.push(idx);return text}
function startRound(){state.round++;state.phase='write';state.prompt=newPrompt();state.answers=[];state.votes={};localSubmitted=false;localVoted=false;broadcast();showWrite();startTimer(state.writeTime)}
function showWrite(){screen('game');$('#roundLabel').textContent=`Manche ${state.round}/${state.totalRounds}`;$('#promptText').textContent=state.prompt;$('#answer').value='';$('#answer').disabled=false;$('#submitBtn').disabled=false;$('#hintBtn').disabled=false;$('#panicBtn').disabled=false;$('#inspiration').classList.add('hidden');$('#submittedState').classList.add('hidden');$('#waitingAnswers').classList.remove('hidden');renderWriteProgress()}
function startTimer(seconds){clearInterval(timerHandle);let end=Date.now()+seconds*1000;tick();timerHandle=setInterval(tick,250);function tick(){let left=Math.max(0,Math.ceil((end-Date.now())/1000));$('#timer').textContent=left;$('#timer').classList.toggle('low',left<=15);if(left<=0){clearInterval(timerHandle);if(mode==='host'&&state.phase==='write')beginVote()}}}
$('#hintBtn').onclick=()=>{$('#inspiration').textContent='🧠 '+pick(D.hints);$('#inspiration').classList.remove('hidden')}
$('#panicBtn').onclick=()=>{$('#inspiration').textContent='🚨 '+pick(D.panics);$('#inspiration').classList.remove('hidden')}
$('#submitBtn').onclick=submitAnswer;
function submitAnswer(){let text=$('#answer').value.trim();if(!text)return toast('Écris quelque chose, même une catastrophe.');if(localSubmitted)return;localSubmitted=true;$('#answer').disabled=true;$('#submitBtn').disabled=true;$('#hintBtn').disabled=true;$('#panicBtn').disabled=true;$('#submittedState').classList.remove('hidden');if(mode==='host'){state.answers.push({id:id(),playerId:me.id,text});broadcast();renderWriteProgress();if(state.answers.length===state.players.length)beginVote()}else hostConn.send({type:'answer',playerId:me.id,text})}
function renderWriteProgress(){if(!$('#answerProgress'))return;$('#answerProgress').textContent=`${state.answers.length} / ${state.players.length} réponses reçues`}
function beginVote(){clearInterval(timerHandle);if(state.phase!=='write')return;state.phase='vote';// Missing answers become intentional blanks and cannot win.
state.answers=shuffle(state.answers);broadcast();showVote()}
function showVote(){screen('vote');$('#votePrompt').textContent=state.prompt;localVoted=!!state.votes[me.id];$('#answerCards').innerHTML='';state.answers.forEach((a,i)=>{let own=a.playerId===me.id;let el=document.createElement('div');el.className='answer-card '+(!own&&!localVoted?'voteable':'');el.innerHTML=`<div class="meta"><span>SUITE ${i+1}</span>${own?'<span>Ta réponse</span>':''}</div><p>${esc(a.text)}</p>`;if(!own&&!localVoted)el.onclick=()=>castVote(a.id,el);$('#answerCards').appendChild(el)});if(state.answers.length<2)$('#answerCards').insertAdjacentHTML('beforeend','<div class="notice">Pas assez de réponses pour voter.</div>')}
function castVote(answerId,el){if(localVoted)return;localVoted=true;$$('.answer-card').forEach(x=>x.classList.remove('voteable'));el.classList.add('selected');if(mode==='host'){state.votes[me.id]=answerId;broadcast();if(Object.keys(state.votes).length===state.players.length)finishVote()}else hostConn.send({type:'vote',playerId:me.id,answerId})}
function finishVote(){if(state.phase!=='vote')return;for(const aid of Object.values(state.votes)){let a=state.answers.find(x=>x.id===aid);if(a)state.scores[a.playerId]=(state.scores[a.playerId]||0)+1}state.phase='results';broadcast();showResults()}
function showResults(){screen('results');let counts={};Object.values(state.votes).forEach(a=>counts[a]=(counts[a]||0)+1);let sorted=[...state.answers].sort((a,b)=>(counts[b.id]||0)-(counts[a.id]||0));let top=counts[sorted[0]?.id]||0;$('#winnerTitle').textContent=top?`🏆 ${top} vote${top>1?'s':''} pour la meilleure catastrophe`:'Personne n’a réussi à voter. Magnifique.';$('#resultCards').innerHTML=sorted.map(a=>{let p=state.players.find(x=>x.id===a.playerId)||{nick:'Disparu',avatar:'👻'};return `<div class="answer-card"><div class="meta"><span>${p.avatar} <b>${esc(p.nick)}</b></span><span class="score">${counts[a.id]||0} vote${(counts[a.id]||0)>1?'s':''}</span></div><p>${esc(a.text)}</p></div>`}).join('');$('#nextRoundBtn').classList.toggle('hidden',mode!=='host');$('#guestNext').classList.toggle('hidden',mode==='host');$('#nextRoundBtn').textContent=state.round>=state.totalRounds?'Voir le classement':'Manche suivante'}
$('#nextRoundBtn').onclick=()=>{state.round>=state.totalRounds?finishGame():startRound()}
function finishGame(){state.phase='final';broadcast();showFinal()}
function showFinal(){screen('final');let arr=[...state.players].sort((a,b)=>(state.scores[b.id]||0)-(state.scores[a.id]||0));$('#leaderboard').innerHTML=arr.map((p,i)=>`<div class="leader"><span>${i===0?'👑 ':''}${p.avatar} <b>${esc(p.nick)}</b></span><span class="score">${state.scores[p.id]||0} pts</span></div>`).join('');$('#restartBtn').classList.toggle('hidden',mode!=='host')}
$('#restartBtn').onclick=()=>{state.round=0;state.phase='lobby';state.usedPrompts=[];state.answers=[];state.votes={};Object.keys(state.scores).forEach(k=>state.scores[k]=0);broadcast();enterLobby()}
function routeState(){if(state.phase==='lobby')enterLobby();else if(state.phase==='write'){if(!$('#game').classList.contains('active')){localSubmitted=state.answers.some(a=>a.playerId===me.id);showWrite();if(localSubmitted){$('#answer').disabled=true;$('#submitBtn').disabled=true;$('#submittedState').classList.remove('hidden')}}renderWriteProgress()}else if(state.phase==='vote')showVote();else if(state.phase==='results')showResults();else if(state.phase==='final')showFinal()}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
